
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER mini_yjy IDENTIFIED BY mini1234;

GRANT CONNECT, RESOURCE, CREATE VIEW TO mini_yjy;

ALTER USER mini_yjy DEFAULT
TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

