
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER mini_yjy IDENTIFIED BY mini1234;

GRANT CONNECT, RESOURCE, CREATE VIEW TO mini_yjy;

ALTER USER mini_yjy DEFAULT
TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

-- 예약 명단 테이블
CREATE TABLE "RESERVATION"(
	RES_NO DATE DEFAULT SYSDATE PRIMARY KEY ,--예약번호
	RES_NM VARCHAR2(30) NOT NULL,--예약 이름
	RES_DATE VARCHAR2(30) NOT NULL,--예약 날짜
	RES_TIME VARCHAR2(10) NOT NULL,--예약 시간
	RES_NUMOF NUMBER(10) NOT NULL,-- 예약인원
	RES_CANCEL CHAR(1) DEFAULT 'N' CHECK(RES_CANCEL IN ('Y', 'N'))--예약 취소
);

COMMENT ON COLUMN  "RESERVATION".RES_NO IS '예약 번호';
COMMENT ON COLUMN  "RESERVATION".RES_NM IS '예약자 이름';
COMMENT ON COLUMN  "RESERVATION".RES_DATE IS '예약 날짜';
COMMENT ON COLUMN  "RESERVATION".RES_TIME IS '예약 시간';
COMMENT ON COLUMN  "RESERVATION".RES_NUMOF IS '예약 인원';
COMMENT ON COLUMN  "RESERVATION".RES_CANCEL IS '예약 취소 여부(Y/N)';

CREATE SEQUENCE SEQ_RES_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

INSERT INTO "RESERVATION"
VALUES(DEFAULT||SEQ_RES_NO.NEXTVAL, '홍길동', '9월 27일', '3시', '4', DEFAULT);



SELECT * FROM RESERVATION;

DROP TABLE "RESERVATION";

ROLLBACK;


INSERT INTO "RESERVATION"


ALTER TABLE "RESERVATION" ADD RES_PHON VARCHAR2(20) DEFAULT ' ' NOT NULL;



UPDATE "RESERVATION" SET
RES_CANCEL = 'Y'
WHERE RES_NO = 15




COMMIT;
SELECT * FROM RESERVATION;

ALTER TABLE "RESERVATION" MODIFY []







